---
abstract: 'Perl extension to wrap libdisasm - an X86 Disassembler'
author:
  - 'Bob Wilkinson <bob@fourtheye.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X86-Disasm
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.23.1
